name: "Terraform Apply Staging"

on:
  push:
    branches:
      - main
    paths:
      - "staging/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

env:
  terraform-version: 1.0.8
  working-directory: staging
  aws-region: ap-northeast-1

jobs:
  apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    env:
      workdir: staging

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Terraform Apply"
        uses: ./.github/actions/terraform-apply
        id: apply
        with:
          terraform-version: ${{ env.terraform-version }}
          working-directory: ${{ env.working-directory }}
          aws-assume-role-arn: ${{ secrets.STG_AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.aws-region }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
