name: "Terraform Plan(Dependabot)"

on: pull_request_target

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

env:
  terraform-version: 1.0.8
  aws-region: ap-northeast-1

jobs:
  plan-develop:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v2
        with:
          # Check out the pull request HEAD
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: "Terraform Plan"
      #   uses: ./.github/actions/terraform-plan
      #   id: plan
      #   with:
      #     terraform-version: ${{ env.terraform-version }}
      #     working-directory: ${{ matrix.working-directory }}
      #     aws-assume-role-arn: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      #     aws-region: ${{ env.aws-region }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Terraform Plan"
        uses: ./.github/actions/terraform-plan
        id: plan
        with:
          terraform-version: ${{ env.terraform-version }}
          working-directory: develop
          aws-assume-role-arn: ${{ secrets.DEV_AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.aws-region }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  plan-staging:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v2
        with:
          # Check out the pull request HEAD
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Terraform Plan"
        uses: ./.github/actions/terraform-plan
        id: plan
        with:
          terraform-version: ${{ env.terraform-version }}
          working-directory: staging
          aws-assume-role-arn: ${{ secrets.STG_AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.aws-region }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  plan-production:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v2
        with:
          # Check out the pull request HEAD
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Terraform Plan"
        uses: ./.github/actions/terraform-plan
        id: plan
        with:
          terraform-version: ${{ env.terraform-version }}
          working-directory: production
          aws-assume-role-arn: ${{ secrets.PRO_AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.aws-region }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
