name: "Terraform Plan Production"

on:
  pull_request:
    paths:
      - "production/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

env:
  terraform-version: 1.0.8
  working-directory: production
  aws-region: ap-northeast-1

jobs:
  plan:
    name: "Terraform Plan production"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v2

      - name: "Terraform Plan"
        uses: ./.github/actions/terraform-plan
        id: plan
        with:
          terraform-version: ${{ env.terraform-version }}
          working-directory: ${{ env.working-directory }}
          aws-assume-role-arn: ${{ secrets.PRO_AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.aws-region }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: tfsec
        # 手動による実行時はコメント先がなく失敗するためプルリクのイベントのみ実行
        if: github.event_name == 'pull_request'
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tfsec_version: latest
